// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTable = "table"

// Table mapped from table <table>
type Table struct {
	ID         int32  `gorm:"column:id;type:INTEGER;primaryKey" json:"id"`
	ProjectID  int32  `gorm:"column:project_id;type:INTEGER" json:"projectId"`
	Project Project `json:"project"`
	Name string `gorm:"column:name;type:string;size:120" json:"name"` //table_name
	Title      string `gorm:"column:title;type:string;size:20" json:"title"`
	Module     string `gorm:"column:module;type:string;size:20" json:"module"`
	Method    []Method `json:"method" form:"method" gorm:"serializer:json"`
	Columns   []Column `json:"columns" form:"columns" gorm:"serializer:json"`
	Types     []string `json:"types" form:"types" gorm:"serializer:json"` // 支持的数据类型
}

// TableName Table's table name
// func (*Table) TableName() string {
// 	return TableNameTable
// }
